openapi: 3.0.0
info:
  title: Green-Lit API
  description: API for Green-Lit application
  version: "1.0"
  
servers:
  - url: https://greenlit-cqvvia6i.b4a.run/
paths:
  /:
    get:
      summary: Welcome message
      responses:
        '200':
          description: OK
          content:
            application/json: {}
  /users/{id}:
    get:
      summary: Get User by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                user:
                  summary: An example of a user
                  value:
                    ID: 1
                    Email: "test@example.com"
                    FullName: "Test User"
                    Gender: "Male"
        '400':
          description: Bad Request (e.g., invalid ID format)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found (user not found)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /articles/users/{id}:
    get:
      summary: Get Articles by User ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
              examples:
                articles:
                  summary: An example of articles
                  value:
                    - ID: "article1"
                      Title: "Article 1"
                      Content: "This is the content of Article 1"
                      PublishedAt: "2023-01-01"
                      Author: 1
        '400':
          description: Bad Request (e.g., invalid ID format)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found (user not found or no articles)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /users:
    get:
      summary: Get All Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /articles:
    get:
      summary: Get All Articles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
              examples:
                articles:
                  summary: An example of articles
                  value:
                    - ID: "article1"
                      Title: "Article 1"
                      Content: "This is the content of Article 1"
                      PublishedAt: "2023-01-01"
                      Author: 1

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Create Article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewArticleRequest'
      responses:
        '201':
          description: Created
          # Add response schema details here (e.g., created Article)
        '400':
          description: Bad Request (e.g., validation error in request body)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


          # Add response schema details here (e.g., created Article)
  /articles/{id}:
    get:
      summary: Get Article by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
              examples:
                article:
                  summary: An example of an article
                  value:
                    ID: "article1"
                    Title: "Article 1"
                    Content: "This is the content of Article 1"
                    PublishedAt: "2023-01-01"
                    Author: 1
  /auth-signIn:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
              examples:
                login:
                  summary: An example of a login response
                  value:
                    AccessToken: "access_token_example"
                    RefreshToken: "refresh_token_example"

components:
  parameters:
    userId:
      in: path
      name: userId
      required: true
      schema:
        type: integer
        format: int32
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    User:
      type: object
      properties:
        ID:
          type: integer
          format: int32
        Email:
          type: string
        FullName:
          type: string
        Gender:
          type: string
    Article:
      type: object
      properties:
        ID:
          type: string
        Title:
          type: string
        Content:
          type: string
        PublishedAt:
          type: string
        Author:
          type: integer
          format: int32
    Login:
      type: object
      properties:
        AccessToken:
          type: string
        RefreshToken:
          type: string
    NewArticleRequest:
      type: object
      required:
        - title
        - content
        - author
      properties:
        title:
          type: string
        content:
          type: string
        author:
          type: integer
          format: int32
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string


# Add additional sections like security if needed
